version: "3.8"

services:
  db:
    image: mysql:8
    container_name: db_boilerplate
    cap_add:
      - SYS_NICE
    restart: always
    expose:
      - "3306"
    ports:
      - "0.0.0.0:3307:3306"
    env_file:
      - ./app/.env
    volumes:
      - db_data:/var/lib/mysqlmysql_db

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: api_boilerplate
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: uvicorn --host=0.0.0.0 app.main:app --reload

volumes:
  db_data:
    driver: local
